/**
 *  @packageDocumentation
 *  @hidden
 *  @ignore
 *  Contains al the different codes for errors.
 */

/**
 *   Different code errors.
 */
const ERROR_CODES = {
  NOT_DEFINED: 'NOT_DEFINED',
  INVALID_PARAMS: 'INVALID_PARAMS',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',

  // API ERRORS.
  API_ONLY_HTTPS: 'API_ONLY_HTTPS',
  API_METHOD_NOT_FOUND: 'API_METHOD_NOT_FOUND',
  API_REQUESTS_TOO_OFTEN: 'API_REQUESTS_TOO_OFTEN',
  API_INVALID_PARAMS: 'API_INVALID_PARAMS',

  // EXTRACTOR ERRORS.
  EXTRACTOR_DOCX_ERROR: 'EXTRACTOR_DOCX_ERROR',
  EXTRACTOR_PDF_ERROR: 'EXTRACTOR_PDF_ERROR',
  EXTRACTOR_DOC_ERROR: 'EXTRACTOR_DOC_ERROR',
  EXTRACTOR_MSG_ERROR: 'EXTRACTOR_MSG_ERROR',
  EXTRACTOR_RTF_ERROR: 'EXTRACTOR_RTF_ERROR',
  EXTRACTOR_OFFICE_PARSER_ERROR: 'EXTRACTOR_OFFICE_PARSER_ERROR',
  EXTRACTOR_INVALID_URL: 'EXTRACTOR_INVALID_URL',
  EXTRACTOR_URL_ERROR: 'EXTRACTOR_URL_ERROR',
  EXTRACTOR_FILE_ERROR: 'EXTRACTOR_FILE_ERROR',
  EXTRACTOR_URL_CODE_NOT_200: 'EXTRACTOR_URL_CODE_NOT_200',
  EXTRACTOR_INVALID_TYPE: 'EXTRACTOR_INVALID_TYPE',
} as const;

export default ERROR_CODES;
